# Cloud Build configuration for Video Processor Service
# Builds and deploys to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-processor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-processor:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/video-processor:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/video-processor:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'video-processor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/video-processor:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'BUCKET_NAME=$PROJECT_ID.appspot.com,NODE_ENV=production,RAPIDAPI_KEY=${_RAPIDAPI_KEY}'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/video-processor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/video-processor:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'

# Substitution variables - set RAPIDAPI_KEY in Cloud Build trigger or via command line:
# gcloud builds submit --substitutions=_RAPIDAPI_KEY=your-api-key
substitutions:
  _RAPIDAPI_KEY: ''
